version: '3.8'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    depends_on:
      - redis
    env_file: 
      - ./.env.docker
    networks:
      - backend  
    environment:
      MYSQL_DATABASE: go_template
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
        

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - backend
    ports:
      - '6379:6379'

  # wait-for-db:
  #   image: atkrad/wait4x
  #   depends_on:
  #     - db
  #   command: tcp db:3306 -t 60s -i 500ms
  #   networks:
  #     - backend

  # app:
  #   build: .
  #   restart: always
  #   env_file:
  #     - ./.env.docker
  #   depends_on:
  #     wait-for-db:
  #       condition: service_completed_successfully
  #   networks:
  #     - backend
  #   ports:
  #     - '9000:9000'
networks:
  backend:

   