package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	"go-template/daos"
	"go-template/gqlmodels"
	"go-template/internal/middleware/auth"
	"go-template/pkg/utl/cnvrttogql"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodels.Author, error) {
	authorID := auth.AuthorIDFromContext(ctx)
	author, err := daos.FindAuthorById(authorID, ctx)
	if err != nil {
		return nil, err
	}
	return cnvrttogql.AuthorToGraphQlAuthor(author, 0), nil

}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context, pagination *gqlmodels.AuthorPagination) (*gqlmodels.AuthorsPayload, error) {
	panic(fmt.Errorf("not implemented: Authors - authors"))
}

// AuthorSearch is the resolver for the authorSearch field.
func (r *queryResolver) AuthorSearch(ctx context.Context, filter *gqlmodels.AuthorFilter) (*gqlmodels.AuthorsPayload, error) {
	panic(fmt.Errorf("not implemented: AuthorSearch - authorSearch"))
}

// Query returns gqlmodels.QueryResolver implementation.
func (r *Resolver) Query() gqlmodels.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
