// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Authors        string
	GorpMigrations string
	Posts          string
	Roles          string
}{
	Authors:        "authors",
	GorpMigrations: "gorp_migrations",
	Posts:          "posts",
	Roles:          "roles",
}
